#!/usr/bin/env bash
#
# Regenerate the "Language Breakdown" table in README.md from the current
# tracked source. Counts lines per file type (git-tracked, __pycache__
# excluded) and rewrites the block between the LANG-STATS markers in place.
#
# Run from anywhere in the repo after any change that adds/removes/resizes
# source files:
#
#   bash scripts/lang-stats.sh
#
# The table is line-based (comments + blanks included). The "GitHub bar"
# column reflects GitHub Linguist: only `programming`/`markup` types appear in
# the repo language bar; `data` (SQL, YAML, JSON) and `prose` (Markdown) do not.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
readme="$repo_root/README.md"
cd "$repo_root"

# ext-or-basename | Label | counted-by-github(yes/no) | Kind
specs=(
  "py|Python|yes|Programming language"
  "sql|SQL|no|Query language"
  "yml|YAML|no|Data / config format"
  "yaml|YAML|no|Data / config format"
  "sh|Shell|yes|Scripting language"
  "md|Markdown|no|Markup (prose)"
  "json|JSON|no|Data format"
  "Dockerfile|Dockerfile|yes|Config DSL"
)

declare -A lines label counted kind
order=()

for spec in "${specs[@]}"; do
  IFS='|' read -r ext lbl cnt knd <<<"$spec"
  # Match "*.ext" or a bare "Dockerfile" basename.
  files=$(git ls-files | grep -v '__pycache__' | grep -iE "\.${ext}$|/${ext}$|^${ext}$" || true)
  [ -z "$files" ] && continue
  n=$(echo "$files" | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
  if [ -n "${lines[$lbl]:-}" ]; then
    lines[$lbl]=$(( lines[$lbl] + n ))
  else
    lines[$lbl]=$n
    label[$lbl]=$lbl
    counted[$lbl]=$cnt
    kind[$lbl]=$knd
    order+=("$lbl")
  fi
done

# Total lines across all types.
total=0
for lbl in "${order[@]}"; do total=$(( total + lines[$lbl] )); done

# Sort labels by line count descending.
sorted=$(for lbl in "${order[@]}"; do echo "${lines[$lbl]} $lbl"; done | sort -rn | awk '{print $2}')

# Build the markdown block.
{
  echo "<!-- LANG-STATS:START (auto-generated by scripts/lang-stats.sh — do not edit by hand) -->"
  echo
  echo "| Type | Kind | Lines | Share | In GitHub bar? |"
  echo "| --- | --- | ---: | ---: | :---: |"
  for lbl in $sorted; do
    n=${lines[$lbl]}
    pct=$(awk -v n="$n" -v t="$total" 'BEGIN{printf "%.1f", (n*100.0)/t}')
    mark=$([ "${counted[$lbl]}" = "yes" ] && echo "✅" || echo "—")
    printf "| %s | %s | %s | %s%% | %s |\n" "$lbl" "${kind[$lbl]}" "$n" "$pct" "$mark"
  done
  printf "| **Total** | | **%s** | **100%%** | |\n" "$total"
  echo
  echo "> **Why GitHub shows only Python/Dockerfile/Shell:** GitHub's language bar"
  echo "> is computed by [Linguist](https://github.com/github-linguist/linguist),"
  echo "> which counts only \`programming\`/\`markup\` file types. SQL, YAML and JSON"
  echo "> are \`data\`, and Markdown is \`prose\` — all excluded — so the bar"
  echo "> renormalizes over the ✅ rows only and hides most of this project's actual"
  echo "> transformation logic (dbt SQL) and configuration."
  echo
  echo "<!-- LANG-STATS:END -->"
} > /tmp/lang-stats-block.md

# Splice the block into README between the markers (create the section if absent).
if grep -q 'LANG-STATS:START' "$readme"; then
  awk '
    /LANG-STATS:START/ { print_block=1; while ((getline line < "/tmp/lang-stats-block.md") > 0) print line; skip=1 }
    /LANG-STATS:END/   { skip=0; next }
    skip==1 { next }
    { print }
  ' "$readme" > "$readme.tmp" && mv "$readme.tmp" "$readme"
else
  echo "No LANG-STATS markers in README.md — add a '## Language Breakdown' section with the markers first." >&2
  exit 1
fi

echo "Updated Language Breakdown ($total total lines)."
